### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by themeer** [bizley/yii2-podium-api#2]
Hey Bizley, can you give some examples/steps of how to integrate this API in my Yii2 project? Thanks

**Comment by bizley** [comment]
It's still WIP stage, so you must be patient ;) Docs will be there when Podium is ready.

**Comment by fedornabilkin** [comment]
Привет. Может быть какая-то часть готова и полноценно работает? Я не против начать интеграцию со своим самописным движком, возможно это поможет найти ошибки на ранней стадии разработки.

**Comment by bizley** [comment]
Hi. API is missing some account part connections with the rest of components. Also polls component needs more tests. I can not guarantee something will not change without any warnings so use it now on your risk.

(and please use English next time)

**Comment by fedornabilkin** [comment]
Hi. What is the current stage of development? Will it be abandoned as well as the previous version of the forum?

**Comment by bizley** [comment]
No, absolutely not. I'm sorry I left it for so long. I'm starting to work on this again.

**Comment by bizley** [comment]
Project is now available at https://github.com/yii-podium/yii2-api
Base API is ready, AR implementation in progress, clients TBA.
