### ISSUE TITLE
Coding practice

### ISSUE THREAD

**Issue by davidnewcomb** [bizley/yii2-podium-api#3]
Hurray, I'm pleased to see you have started these 2 projects!

I'm reading through a lot of the code at the moment and I'm finding it very wordy! I just wanted to let you know about a common practice with interface names. There are typically 2 schools of thought:

#|Interface Name | Concrete Name | Background
-|-|-|-
1|IMembership | Membership | C++
2|Membership | MembershipImpl | Java

So for a line of code like:
`public function create(array $data, MembershipInterface $author, ModelInterface $thread)`
it would be clarified into
`public function create(array $data, IMembership $author, IModel $thread)`
or
`public function create(array $data, Membership $author, Model $thread)`

I hope you don't think I'm trying to teach your grandma to suck eggs, but it makes the code a lot easier to read.

Just something to think about.

**Comment by bizley** [comment]
Thanks for this, it really made me giggle 😁 I find it really heartwarming that you truly care about naming convention and on top of that it's reassuring that this coding community still keep the good standards. I used to use C++ style interfaces names as well but few years ago I switched to `AbcInterface` convention that is recommended as PSR by PHP-FIG.

https://www.php-fig.org/bylaws/psr-naming-conventions/
