### ISSUE TITLE
First Release ETA

### ISSUE THREAD

**Issue by mtangoo** [bizley/yii2-podium-api#4]
When should we expect first release? Checking readme it seems that the checklist is all done.
What is remaining?

**Comment by bizley** [comment]
Really hard to say. Most work right now for this repo is happening in https://github.com/bizley/yii2-podium-api/tree/handlers-everywhere branch when I'm rewriting it a bit for better handling and less interfaces. I would like API to be released together with client to make sure both are properly usable.
